# Generated by Django 5.0.6 on 2026-09-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(help_text='Signed: positive = income, negative = expense')),
                ('type', models.CharField(choices=[('REWARD', 'Mukofot'), ('WITHDRAWAL', 'Pul yechish'), ('REFUND', 'Qaytarish'), ('ADJUSTMENT', 'Balansni tuzatish')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('COMPLETED', 'Bajarildi'), ('FAILED', 'Muvaffaqiyatsiz')], default='COMPLETED', max_length=16)),
                ('reference', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transactions_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
