# Generated by Django 5.0.6 on 2026-09-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve_report', 'Arizani tasdiqlash'), ('reject_report', 'Arizani rad etish'), ('withdrawal_approve', 'Yechib olishni tasdiqlash'), ('withdrawal_reject', 'Yechib olishni rad etish'), ('withdrawal_paid', "To'lovni belgilash"), ('adjust_balance', 'Balansni tuzatish'), ('user_update', 'Foydalanuvchini tahrirlash')], max_length=32)),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.PositiveBigIntegerField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rewards_admin_action_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rewards_reward',
                'ordering': ['-created_at'],
            },
        ),
    ]
