# Generated by Django 5.0.6 on 2026-09-23 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wasteimage',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.wastereport'),
        ),
        migrations.AddField(
            model_name='location',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='reports.wastereport'),
        ),
        migrations.AddConstraint(
            model_name='wastereport',
            constraint=models.CheckConstraint(check=models.Q(('latitude__range', (-90, 90))), name='report_lat_range'),
        ),
        migrations.AddConstraint(
            model_name='wastereport',
            constraint=models.CheckConstraint(check=models.Q(('longitude__range', (-180, 180))), name='report_lng_range'),
        ),
    ]
